# type: ignore
"""add ace playbook tables

Revision ID: 98ba423688c9
Revises: f1g2h3i4j5k6
Create Date: 2025-11-17 02:50:00.657835+00:00

"""
from __future__ import annotations

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC
from sqlalchemy import Text  # noqa: F401

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText

# revision identifiers, used by Alembic.
revision = '98ba423688c9'
down_revision = 'f1g2h3i4j5k6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ace_playbook_revision',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('applied_by', sa.String(length=255), nullable=True),
    sa.Column('operations', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ace_playbook_revision'))
    )
    with op.batch_alter_table('ace_playbook_revision', schema=None) as batch_op:
        batch_op.create_index('ix_ace_playbook_revision_created_at', ['created_at'], unique=False)

    op.create_table('ace_playbook_section',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ordering', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ace_playbook_section')),
    sa.UniqueConstraint('name', name='uq_ace_playbook_section_name')
    )
    op.create_table('ace_playbook_bullet',
    sa.Column('id', sa.GUID(length=16), nullable=False),
    sa.Column('bullet_id', sa.String(length=128), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('section_id', sa.GUID(length=16), nullable=False),
    sa.Column('helpful_count', sa.Integer(), nullable=False),
    sa.Column('harmful_count', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('sa_orm_sentinel', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['ace_playbook_section.id'], name=op.f('fk_ace_playbook_bullet_section_id_ace_playbook_section'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ace_playbook_bullet')),
    sa.UniqueConstraint('bullet_id', name='uq_ace_playbook_bullet_identifier')
    )
    with op.batch_alter_table('ace_playbook_bullet', schema=None) as batch_op:
        batch_op.create_index('ix_ace_playbook_bullet_section_created_at', ['section_id', 'created_at'], unique=False)

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ace_playbook_bullet', schema=None) as batch_op:
        batch_op.drop_index('ix_ace_playbook_bullet_section_created_at')

    op.drop_table('ace_playbook_bullet')
    op.drop_table('ace_playbook_section')
    with op.batch_alter_table('ace_playbook_revision', schema=None) as batch_op:
        batch_op.drop_index('ix_ace_playbook_revision_created_at')

    op.drop_table('ace_playbook_revision')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
